# Generated by Django 3.1.3 on 2020-11-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201121_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('note', models.CharField(max_length=100, verbose_name='Short description')),
                ('body', models.TextField()),
                ('featured_img', models.ImageField(upload_to='')),
                ('category', models.ManyToManyField(to='core.Category')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
